version: "3.4"
services:
  mysql:
    image: mysql:5
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/init-files:/docker-entrypoint-initdb.d
    env_file:
      - ./mysql/.env
    ports:
      - "3306:3306"
    networks:
      - app-tier
  back:
    depends_on:
      - mysql
    build: ./back
    container_name: back
    env_file:
      - ./mysql/.env
    environment:
      SERVICE_PORT: "3000"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-tier 
  front:
    depends_on:
      - back
    build: ./front
    container_name: front
    env_file:
      - ./mysql/.env
    environment:
      SERVICE_PORT: "3001"
    ports:
      - "3001:3001"
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge