- name: add sample data to database  
  copy: src=roles/mysql/files/dump.sql dest=/tmp/dump.sql

- name: Running sql script
  mysql_db:
    login_host: "{{ host }}"
    login_user: "{{ user }}"
    login_password: "{{ password }}"
    name: all
    state: import
    target: /tmp/dump.sql